#spring.datasource.url=your-existing-url
#spring.datasource.username=your-existing-username

spring.application.name=spacefinder
spring.data.mongodb.uri=mongodb+srv://${BOT_USERNAME}:${BOT_PASSWORD}@datacluster.d2bhkt7.mongodb.net/?appName=DataCluster
#spring.data.mongodb.database=Data

#logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

