### 1. Test GET All Spaces
# This checks if the controller can fetch basic data
GET http://localhost:8080/api/spaces
Accept: application/json

---

### 2. Test POST Recommended Search
# tests Advanced Search
POST http://localhost:8080/api/spaces/recommendedSearch
Content-Type: application/json

{
  "searchBarBuildingQuery": "library",
  "filters": {
    "preferredNoiseLevel": "QUIET",
    "preferredOccupancy": "EMPTY",
    "preferredGroupSpace": true,
    "preferredGroupSize": 4
  }
}