export const SPACES = [
  {
    id: "1",
    roomLocation: "Library Study Room",
    building: "Claverton Down",
    address: "Claverton Down, University Campus",
    about:
      "A quiet study room inside the main library. Ideal for focused work with plenty of desks, natural light, and power outlets.",
    rating: 4.3,
    reviewCount: 47,
    occupancy: "Free",
    distance: "4 m",
    walkTime: "3 mins",
    atmosphere: "Quiet",
    people: "2-3",
    peopleMin: 1,
    peopleMax: 3,
    foodPolicy: "Drinks Only",
    imageUrl:
      "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=600&q=60",
    amenities: ["wheelchairAccess", "monitor", "whiteboard", "powerOutlets"],
    lat: 51.3782,
    lng: -2.327,
  },
  {
    id: "2",
    roomLocation: "Quiet Study Corner",
    building: "Chancellors’ Building",
    address: "Chancellors’ Building, University Campus",
    about:
      "A small and peaceful study corner perfect for independent study sessions. Best during mornings.",
    rating: 4.6,
    reviewCount: 32,
    occupancy: "Busy",
    distance: "6 m",
    walkTime: "5 mins",
    atmosphere: "Silent",
    people: "1",
    peopleMin: 1,
    peopleMax: 1,
    foodPolicy: "No Food/Drinks",
    imageUrl:
      "https://images.unsplash.com/photo-1492724441997-5dc865305da7?auto=format&fit=crop&w=600&q=60",
    amenities: ["monitor", "powerOutlets"],
    lat: 51.3785,
    lng: -2.3265,
  },
  {
    id: "3",
    roomLocation: "Group Collaboration Room",
    building: "8 West",
    address: "8 West Building, University Campus",
    about:
      "Designed for teamwork and brainstorming. Includes whiteboards and large monitors for presentations.",
    rating: 4.1,
    reviewCount: 21,
    occupancy: "Free",
    distance: "2 m",
    walkTime: "1 min",
    atmosphere: "Collaborative",
    people: "6-8",
    peopleMin: 1,
    peopleMax: 8,
    foodPolicy: "Food Allowed",
    imageUrl:
      "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=600&q=60",
    amenities: ["whiteboard", "monitor", "powerOutlets"],
    lat: 51.3779,
    lng: -2.3281,
  },
  {
    id: "4",
    roomLocation: "Silent Reading Room",
    building: "Library Level 5",
    address: "Library Level 5, University Campus",
    about:
      "Strict silent zone for deep focus reading and exam preparation. Comfortable seating and calm atmosphere.",
    rating: 4.8,
    reviewCount: 63,
    occupancy: "Free",
    distance: "1 m",
    walkTime: "1 min",
    atmosphere: "Silent",
    people: "1",
    peopleMin: 1,
    peopleMax: 1,
    foodPolicy: "No Food/Drinks",
    imageUrl:
      "https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&w=600&q=60",
    amenities: ["wheelchairAccess", "powerOutlets"],
    lat: 51.3783,
    lng: -2.3274,
  },
  {
    id: "5",
    roomLocation: "Engineering Study Hub",
    building: "4 West",
    address: "4 West Building, University Campus",
    about:
      "Popular among engineering students. Equipped with collaborative tables and whiteboards.",
    rating: 4.0,
    reviewCount: 18,
    occupancy: "Busy",
    distance: "7 m",
    walkTime: "6 mins",
    atmosphere: "Moderate",
    people: "4-5",
    peopleMin: 1,
    peopleMax: 5,
    foodPolicy: "Drinks Only",
    imageUrl:
      "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=600&q=60",
    amenities: ["monitor", "whiteboard", "powerOutlets"],
    lat: 51.3775,
    lng: -2.329,
  },
  {
    id: "6",
    roomLocation: "Window Study Space",
    building: "1 East",
    address: "1 East Building, University Campus",
    about:
      "Bright study area with large windows and natural sunlight. Ideal for relaxed productivity.",
    rating: 3.9,
    reviewCount: 12,
    occupancy: "Free",
    distance: "5 m",
    walkTime: "4 mins",
    atmosphere: "Quiet",
    people: "2-3",
    peopleMin: 1,
    peopleMax: 3,
    foodPolicy: "Drinks Only",
    imageUrl:
      "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?auto=format&fit=crop&w=600&q=60",
    amenities: ["powerOutlets"],
    lat: 51.3788,
    lng: -2.3262,
  },
  {
    id: "7",
    roomLocation: "Creative Thinking Room",
    building: "The Edge",
    address: "The Edge Building, University Campus",
    about:
      "A flexible creative space designed for brainstorming and innovative projects.",
    rating: 4.7,
    reviewCount: 54,
    occupancy: "Busy",
    distance: "3 m",
    walkTime: "2 mins",
    atmosphere: "Collaborative",
    people: "6-8",
    peopleMin: 1,
    peopleMax: 8,
    foodPolicy: "Food Allowed",
    imageUrl:
      "https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=600&q=60",
    amenities: ["whiteboard", "monitor", "powerOutlets"],
    lat: 51.379,
    lng: -2.3258,
  },
  {
    id: "8",
    roomLocation: "Basement Quiet Zone",
    building: "3 South",
    address: "3 South Building, University Campus",
    about:
      "Low-traffic quiet basement space. Best for uninterrupted concentration.",
    rating: 3.8,
    reviewCount: 9,
    occupancy: "Free",
    distance: "8 m",
    walkTime: "7 mins",
    atmosphere: "Quiet",
    people: "1",
    peopleMin: 1,
    peopleMax: 2,
    foodPolicy: "No Food/Drinks",
    imageUrl:
      "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=600&q=60",
    amenities: ["powerOutlets", "wheelchairAccess"],
    lat: 51.3772,
    lng: -2.3287,
  },
  {
    id: "9",
    roomLocation: "Computer Lab Study Area",
    building: "2 East",
    address: "2 East Building, University Campus",
    about:
      "Computer-equipped study space perfect for programming and digital projects.",
    rating: 4.2,
    reviewCount: 36,
    occupancy: "Busy",
    distance: "4 m",
    walkTime: "3 mins",
    atmosphere: "Moderate",
    people: "4-5",
    peopleMin: 1,
    peopleMax: 5,
    foodPolicy: "No Food/Drinks",
    imageUrl:
      "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=600&q=60",
    amenities: ["monitor", "powerOutlets", "wheelchairAccess"],
    lat: 51.3781,
    lng: -2.3269,
  },
  {
    id: "10",
    roomLocation: "Outdoor Study Terrace",
    building: "Student Centre",
    address: "Student Centre, University Campus",
    about:
      "Outdoor terrace seating for fresh-air study sessions during sunny days.",
    rating: 4.5,
    reviewCount: 29,
    occupancy: "Free",
    distance: "9 m",
    walkTime: "8 mins",
    atmosphere: "Moderate",
    people: "8-10",
    peopleMin: 1,
    peopleMax: 10,
    foodPolicy: "Food Allowed",
    imageUrl:
      "https://images.unsplash.com/photo-1496307042754-b4aa456c4a2d?auto=format&fit=crop&w=600&q=60",
    amenities: ["powerOutlets"],
    lat: 51.3795,
    lng: -2.325,
  },
  {
    id: "11",
    roomLocation: "Postgraduate Study Lounge",
    building: "Graduate Centre",
    address: "Graduate Centre, University Campus",
    about:
      "Exclusive lounge space for postgraduate students. Quiet, comfortable, and well-equipped.",
    rating: 4.9,
    reviewCount: 71,
    occupancy: "Free",
    distance: "10 m",
    walkTime: "9 mins",
    atmosphere: "Silent",
    people: "2-3",
    peopleMin: 1,
    peopleMax: 3,
    foodPolicy: "Drinks Only",
    imageUrl:
      "https://images.unsplash.com/photo-1472289065668-ce650ac443d2?auto=format&fit=crop&w=600&q=60",
    amenities: ["monitor", "whiteboard", "powerOutlets", "wheelchairAccess"],
    lat: 51.3798,
    lng: -2.3245,
  },
];